const { config } = require("../../config");

const audiovisuals = [
  {
    name: "avengers endgame",
    type: "movie",
    synopsis:
      "El grave curso de los acontecimientos puesto en marcha por Thanos que destruyó la mitad del universo gracias al las Gemas del Infinito. Ha provocado que los Vengadores restantes deban tomar una última posición en la gran conclusión de Marvel Studios a veintidós películas",
    number_seasons: 0,
    background: `http://localhost:${config.port}/backgrounds/avengers_endgame.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/avengers_endgame.png`,
    logo_mobile: `http://localhost:${config.port}/logos/avengers_endgame.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/avengers_endgame.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/avengers_endgame.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Era de hielo las aventuras de scrat",
    type: "serie",
    synopsis:
      "El grave curso de los acontecimientos puesto en marcha por Thanos que destruyó la mitad del universo gracias al las Gemas del Infinito. Ha provocado que los Vengadores restantes deban tomar una última posición en la gran conclusión de Marvel Studios a veintidós películas",
    number_seasons: 1,
    background: `http://localhost:${config.port}/backgrounds/age_of_ice.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/age_of_ice.png`,
    logo_mobile: `http://localhost:${config.port}/logos/age_of_ice.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/age_of_ice.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/age_of_ice.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Agente carter",
    type: "serie",
    synopsis:
      "Ella es una mujer soltera en Estados Unidos tras perder al amor de su vida Steve Rogers, más conocido como el Capitán América. Su viejo conocido Howard Stark (Dominic Cooper) se encuentra a sí mismo siendo acorralado por haber desatado sus armas más mortíferas que ahora están en manos de las personas equivocadas.",
    number_seasons: 2,
    background: `http://localhost:${config.port}/backgrounds/agent_carter.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/agent_carter.png`,
    logo_mobile: `http://localhost:${config.port}/logos/agent_carter.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/agent_carter.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/agent_carter.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Black widow",
    type: "movie",
    synopsis:
      "Al nacer, la Viuda Negra, también conocida como Natasha Romanova, se entrega a la KGB para convertirse en su agente definitivo. Cuando la URSS se separa, el gobierno intenta matarla mientras la acción se traslada a la actual Nueva York.",
    number_seasons: 0,
    background: `http://localhost:${config.port}/backgrounds/black_widow.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/black_widow.png`,
    logo_mobile: `http://localhost:${config.port}/logos/black_widow.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/black_widow.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/black_widow.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Bobba Fett",
    type: "serie",
    synopsis:
      "El Libro de Boba Fett, una emocionante aventura de Star Wars, encuentra al legendario cazarrecompensas Boba Fett y a la mercenaria Fennec Shand navegando por el inframundo de la galaxia cuando regresan a las arenas de Tatooine para reclamar el territorio que una vez gobernó Jabba el Hutt y su sindicato criminal.",
    number_seasons: 1,
    background: `http://localhost:${config.port}/backgrounds/bobba_fett.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/bobba_fett.png`,
    logo_mobile: `http://localhost:${config.port}/logos/bobba_fett.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/bobba_fett.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/bobba_fett.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Encanto",
    type: "movie",
    synopsis:
      "En lo alto de las montañas de Colombia hay un lugar encantado llamado Encanto. Aquí, en una casa mágica, vive la extraordinaria familia Madrigal donde todos tienen habilidades fantásticas.",
    number_seasons: 0,
    background: `http://localhost:${config.port}/backgrounds/encanto.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/encanto.png`,
    logo_mobile: `http://localhost:${config.port}/logos/encanto.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/encanto.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/encanto.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Hawkeye",
    type: "serie",
    synopsis:
      "Ojo de Halcón es una serie de Marvel que se centra en la historia del superhéroe Clint Barton que se encuentra en Nueva York junto a sus hijos tras los acontecimientos de Vengadores: Endgame, justo después del trágico Lapso.",
    number_seasons: 1,
    background: `http://localhost:${config.port}/backgrounds/hawkeye.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/hawkeye.png`,
    logo_mobile: `http://localhost:${config.port}/logos/hawkeye.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/hawkeye.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/hawkeye.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Jungle Cruise",
    type: "movie",
    synopsis:
      "Película basada en el paseo en un parque temático de Disneyland donde un pequeño barco fluvial lleva a un grupo de viajeros a través de una jungla llena de peligrosos animales y reptiles, pero con un elemento sobrenatural.",
    number_seasons: 0,
    background: `http://localhost:${config.port}/backgrounds/jungle_cruise.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/jungle_cruise.png`,
    logo_mobile: `http://localhost:${config.port}/logos/jungle_cruise.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/jungle_cruise.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/jungle_cruise.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Lilo & Stitch",
    type: "movie",
    synopsis:
      "Lilo es una niña hawaiana que se siente sola y decide adoptar un perro muy feo al que llama Stitch. Este sería la mascota perfecta si no fuera en realidad un experimento genético que ha escapado de un planeta alienígena y que ha llegado a la Tierra por casualidad.",
    number_seasons: 0,
    background: `http://localhost:${config.port}/backgrounds/lilo_&_stitch.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/lilo_&_stitch.png`,
    logo_mobile: `http://localhost:${config.port}/logos/lilo_&_stitch.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/lilo_&_stitch.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/lilo_&_stitch.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Loki",
    type: "serie",
    synopsis:
      "Tras robar el Cubo Cósmico, Loki (Tom Hiddleston) aparece trasladado a un desierto. Allí es detenido y conducido a la Autoridad de Variación Temporal, una organización fuera del espacio-tiempo que le juzgará por sus crímenes. En el proceso, el travieso Loki podrá evitar la eliminación de su existencia si colaobora con la organización con la misión de armonizar el flujo temporal del multiverso. Esto le llevará a participar en eventos claves en la Historia de la humanidad.",
    number_seasons: 1,
    background: `http://localhost:${config.port}/backgrounds/loki.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/loki.png`,
    logo_mobile: `http://localhost:${config.port}/logos/loki.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/loki.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/loki.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Malefica",
    type: "movie",
    synopsis:
      "Maléfica es una joven y poderosa hada que sufre las consecuencias de haberse enamorado de un ser humano ambicioso (Stefan), y entre su pena y dolor decide vengarse haciéndole daño a través de su recién nacida hija (Aurora). Aunque el resto de la historia es conocida por todos, en realidad esta película no funcionaría si no tuviera un “twist” que casi coincidiera con la original, pero que se refiere a otra forma de ver las cosas.",
    number_seasons: 0,
    background: `http://localhost:${config.port}/backgrounds/malefica.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/malefica.png`,
    logo_mobile: `http://localhost:${config.port}/logos/malefica.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/malefica.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/malefica.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "The Mandalorian",
    type: "serie",
    synopsis:
      "Las aventuras de Mando, un pistolero solitario y cazarrecompensas que se abre paso a través de las fronteras más remotas de la galaxia, lejos de la jurisdicción de la Nueva República.",
    number_seasons: 2,
    background: `http://localhost:${config.port}/backgrounds/mandalorian.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/mandalorian.png`,
    logo_mobile: `http://localhost:${config.port}/logos/mandalorian.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/mandalorian.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/mandalorian.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Ralph el demoledor",
    type: "movie",
    synopsis:
      "Cansado de ser el malo de la historia, Ralph decide tomar el asunto en sus propias y gigantes manos y comenzar un viaje a través de los videojuegos que conviven en los recreativos para demostrarle al mundo que él también puede ser un héroe.",
    number_seasons: 0,
    background: `http://localhost:${config.port}/backgrounds/ralph_demoledor.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/ralph_demoledor.png`,
    logo_mobile: `http://localhost:${config.port}/logos/ralph_demoledor.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/ralph_demoledor.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/ralph_demoledor.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Bienvenidos a la Tierra",
    type: "serie",
    synopsis:
      "El actor Will Smith se propone ofrecer una visión de algunos de los lugares más remotos e inexplorados del mundo.",
    number_seasons: 1,
    background: `http://localhost:${config.port}/backgrounds/ralph_demoledor.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/ralph_demoledor.png`,
    logo_mobile: `http://localhost:${config.port}/logos/ralph_demoledor.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/ralph_demoledor.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/ralph_demoledor.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "What If...?",
    type: "serie",
    synopsis:
      "El espacio explora lo que sucedería si los principales momentos de las películas del Universo Cinematográfico de Marvel ocurrieran de manera diferente.",
    number_seasons: 1,
    background: `http://localhost:${config.port}/backgrounds/what_if.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/what_if.png`,
    logo_mobile: `http://localhost:${config.port}/logos/what_if.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/what_if.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/what_if.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Wifi Ralph",
    type: "movie",
    synopsis:
      "Para dar mayor emoción a la vida de su amiga Vanéllope, Ralph decide crear una nueva ruta en su juego Sugar Rush. Sin embargo, las consecuencias de esta decisión serán más preocupantes que divertidas: uno de los mandos del juego se rompe y el señor Litwak decide apagar la máquina para siempre.",
    number_seasons: 0,
    background: `http://localhost:${config.port}/backgrounds/wifi_ralph.jpg`,
    logo_desktop: `http://localhost:${config.port}/logos/wifi_ralph.png`,
    logo_mobile: `http://localhost:${config.port}/logos/wifi_ralph.png`,
    thumbnail_desktop: `http://localhost:${config.port}/thumbnails/wifi_ralph.jpg`,
    thumbnail_mobile: `http://localhost:${config.port}/thumbnails/wifi_ralph.jpg`,
    created_date: "2019-04-26 04:00:00",
    updated_date: "2019-04-26 04:00:00",
    created_at: new Date(),
    updated_at: new Date(),
  },
];
module.exports = audiovisuals;
